routes/web.php
<?php

//Route::get('/', function () {
  //  return view('index');
//})->middleware('guest')->middleware('disablepreventback');

Route::get('/', 'IndexController@index')->middleware('guest')->middleware('disablepreventback');

Auth::routes(['verify' => true]);

Route::get('/pruebaNav', function () {
    return view('usuarioAdmin.Productos.index');
})->middleware('disablepreventback');

Route::get('/cliente', function () {
    return view('usuarioStandar.Cliente.create');
})->middleware('disablepreventback');

// aca cosas qye solo puede ver el administrador
Route::group(['middleware' => 'usuarioAdmin'], function () {
    Route::get('/home','homeController@index')->name('home')->middleware('verified')->middleware('auth')->middleware('disablepreventback');

    Route::resource('Productos','ProductsController')->middleware('auth');
});

// aca termina las vistas solo para e administrador

// aca vistas que solo puede ver el usuario normal

Route::group(['middleware' => 'usuarioStandard'], function () {

    Route::get('/usuario','homeController@standar')->name('usuarioStandar')->middleware('verified')->middleware('auth')->middleware('disablepreventback');

    Route::resource('Cliente','ClientController')->middleware('auth');

});
// aca termina las vistas que puede ver el usuario normal
Route::resource('Perfil','perfilcontroller')->middleware('auth');

Route::get('/CatalogoProductos',[
    'as'=> 'home',
    'uses' => 'CatalogoUserController@index'
])->middleware('auth');

Route::get('/CatalogoProductos/{id}',[
    'as'=> 'product-detail',
    'uses' => 'CatalogoUserController@show'
])->middleware('auth');

Route::resource('CategoriaProductos','ProductCategoryController')->middleware('auth');

Route::resource('usuarioAdmin','PurposesController')->middleware('auth');

Route::resource('ProductoFinal','ProductFinalController')->middleware('auth');

Route::resource('FichaTecnica','DataController')->middleware('auth');

Route::resource('Pedido','statuscontroller')->middleware('auth');

Route::resource('InformeClientes','informeController')->middleware('auth');

Route::resource('TipoInsumos','typesuppliecontroller')->middleware('auth');

Route::resource('Insumos','suppliecontroller')->middleware('auth');

Route::resource('Tarifas','ratecontroller')->middleware('auth');

Route::resource('Pedido','statuscontroller')->middleware('auth');

Route::resource('Pedidos','pedidocontroller')->middleware('auth');

Route::resource('Informes','detalleController')->middleware('auth');

Route::resource('Galeria','galerycontroller');

app/Http/Controllers/perfilcontroller.php
<?php

namespace App\Http\Controllers;

use App\Model\clients;
use Illuminate\Http\Request;
use PhpParser\Node\Stmt\DeclareDeclare;

class perfilcontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuario = \auth::user();

        $cliente = clients::select('users.email','clients.name','clients.lastname','clients.phone','clients.address','clients.avatar')
            ->join('users','users.id','=','clients.id_user')
            ->where('clients.id_user', '=', $usuario->id)
            ->get();

        return view('usuarioStandar.Perfil.index', compact('cliente','usuario'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = \auth::user();
        $usuario2 = \auth::user()->id;
        $clientes = clients::all();
        $clientes = clients::find($id);
        $usuario3 = clients::select('users.email')
            ->join('users','users.id','=','clients.id_user')
            ->where('clients.id_user', '=', $usuario2)
            ->get();

        return view('usuarioStandar.Perfil.edit',compact('clientes','usuario','usuario2','usuario3'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cliente = clients::find($id);
        /**$cliente->avatar = $request->avatar;
        $cliente->id_user = $request->id_user;*/
        $cliente->name = $request->name;
        $cliente->lastname = $request->lastname;
        $cliente->phone = $request->phone;
        $cliente->address = $request->address;
        $cliente->save();
        return redirect()->route('Perfil.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/usuarioStandar/Perfil/edit.blade.php
<form class="" method="POST" action="{{route('Perfil.update',$clientes->id_user)}}" enctype="multipart/form-data">
    {{ csrf_field() }}
    @method('PUT')
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="name" class="col-md-6 control-label">nombre</label>
            <input id="name" type="text" class="form-control" name="name"  value="{{$clientes->name}}">
            <h6 hidden id="nameErr" class="text-danger">Nombre no valido</h6>
        </div>
        <div class="form-group col-md-6">
            <label for="lastname" class="col-md-6 control-label">Apellido</label>
            <input id="lastname" type="text" class="form-control" name="lastname" required autofocus value="{{$clientes->lastname}}">
            <h6 hidden id="lastnameErr" class="text-danger">Apellido no valido</h6>
        </div>
        <div class="form-group col-md-6">
            <label for="number" class="col-md-8 control-label">Numero telefonico</label>
            <input id="phone" type="text" class="form-control" name="phone"  required autofocus onclick="soloNumero()" onkeyup="soloNumero()" onkeypress="soloNumero()" onkeydown="soloNumero()" value="{{$clientes->phone}}">
            <h6 hidden id="phoneErr" class="text-danger">Numero no valido</h6>
        </div>
        <div class="form-group col-md-6">
            <label for="address" class="col-md-6 control-label">Direccion</label>
            <input id="address" type="text" class="form-control" name="address"  required autofocus value="{{$clientes->address}}">
            <h6 hidden id="addressErr" class="text-danger"> Direccion no valida</h6>
        </div>
    </div>
    <div class="col-sm-4" onmouseover="ValidarUsuario()">
        <button id="btnCrearCliente" class="btn btn-success" type="submit" onclick="registroExitoso()">Editar</button>
    </div>
</form>

resources/views/usuarioStandar/Perfil/index.blade.php
@extends('layouts.nav')
@section('name')
    {{-- termina el mostrar --}}
@endsection
@section('contenidoNav')
    <div class="container">
        <div class="card col-md-10 prueba " style=" margin-left: 7.5%">
            <div class="card-header">
                <h6 style="margin-left: 39%" class="text-black-50">Perfil</h6>
            </div>
            <div class="card-body">
                <div class="container">
                    <form class="" method="POST" action="{{route('Perfil.update',$usuario->id)}}" enctype="multipart/form-data" id="formulario">
                        {{ csrf_field() }}
                        @method('PUT')
                        @foreach ($cliente as $clientes)
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    <img class="avatar" src="Avatares/{{$clientes->avatar}}" width="180" height="190" style="border-radius: 20px 30px 10px">
                                    <ul style="margin-left: 8%"><a href="">cambiar</a></ul>
                                </div>
                                <div class="col-sm-8">
                                    <label for="email" class=" control-label">Correo Electronico</label>
                                    <input id="email" type="text" class="form-control" name="email" autofocus readonly value="{{$clientes->email}}">
                                    <br>
                                    <div class="form-group row">
                                        <div class="col-6">
                                            <label for="name" class="col-md-6 control-label">Nombres</label>
                                            <input id="name" type="text" class="form-control" name="name"  value="{{$clientes->name}}"  readonly>
                                            <h6 hidden id="nameErr" class="text-danger">Nombre no valido</h6></div>
                                        <div class="col-6">
                                            <label for="name" class="col-md-6 control-label">Apellidos</label>
                                            <input id="lastname" type="text" class="form-control" name="lastname" required autofocus value="{{$clientes->lastname}}" readonly>                                            <h6 hidden id="nameErr" class="text-danger">Nombre no valido</h6>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-group row">
                                        <div class="col-6">
                                            <label for="name" class="col-md-8 control-label">Numero telefonico</label>
                                            <input id="phone" type="text" class="form-control" name="phone"  required autofocus onclick="soloNumero()" onkeyup="soloNumero()" onkeypress="soloNumero()" onkeydown="soloNumero()" value="{{$clientes->phone}}" readonly>
                                            <h6 hidden id="nameErr" class="text-danger">Numero no valido</h6></div>
                                        <div class="col-6">
                                            <label for="address" class="col-md-6 control-label">Direccion</label>
                                            <input id="address" type="text" class="form-control" name="address"  required autofocus value="{{$clientes->address}}" readonly>
                                            <h6 hidden id="addressErr" class="text-danger"> Direccion no valida</h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-4">

                                </div>
                                <div class="col-8">
                                    <button type="submit" id="btnenviar" hidden></button>
                                </div>
                            </div>
                        @endforeach
                    </form>
                    <div class="row">
                        <div class="col-4"></div>
                        <div class="col-8">
                            <button hidden id="btnCrearCliente" class="btn btn-success" onclick="editar()">Guardar</button>
                            <button class="btn btn-success" id="Edit" onclick="ValidarEditPerfil()">Editar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection